services:
  hanna-med-ma-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_V2_API_URL}
        - VITE_FIREBASE_API_KEY=${VITE_V2_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_V2_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_V2_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_V2_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_V2_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_V2_FIREBASE_APP_ID}
    container_name: hanna-med-ma-client-v2
    restart: unless-stopped
    environment:
      - CLIENT_PORT=${V2_CLIENT_PORT:-3004}
    expose:
      - ${V2_CLIENT_PORT:-3004}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
